# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8a2324abf37f332eee6160ef49173a8f34c594ac381c0a1858fc59230caab8efdf8b9f99fa5751f3db97c7a6b1baa54c02a476fdfdf31c05209d8eef8c1235

test:
  secret_key_base: c9188e5144fe3feed41bbbab10bde6020894cc9b98ab2038bf4a18738a034de4c590fb57612864691ed6f28ba877055abdeaa9b22ba3e7f8d0e80486ebdaaa2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
